//
// Created by dex on 5/26/23.
//

#ifndef SDL_BACHELORDEFENDER_PARTICLESHANDLER_H
#define SDL_BACHELORDEFENDER_PARTICLESHANDLER_H


class particlesHandler {

};


#endif //SDL_BACHELORDEFENDER_PARTICLESHANDLER_H
